# Generated by Django 5.0.7 on 2024-07-27 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="address",
            new_name="message",
        ),
    ]
