# Generated by Django 5.0.7 on 2024-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_address_client_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="message",
            field=models.TextField(),
        ),
    ]
