# Generated by Django 5.0.7 on 2024-07-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_gallery_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="language",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="title",
        ),
        migrations.CreateModel(
            name="GalleryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian")], max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="home.gallery",
                    ),
                ),
            ],
            options={
                "unique_together": {("gallery", "language")},
            },
        ),
    ]
